### ISSUE TITLE
Cannot save items

### ISSUE THREAD

**Issue by RobinRattus** [Ruukas97/Creative-Editor#15]
Don't know what's caused it, just joined a hypixel housing, did /gmc and the save button is gone, worked on other ones
![grafik](https://user-images.githubusercontent.com/78902172/170370609-6ec491ab-7e44-40e5-b431-07afb3e6ad9f.png)
![grafik](https://user-images.githubusercontent.com/78902172/170370779-ad1dfca2-e558-4961-a460-50d9086f4def.png)

**Comment by RobinRattus** [comment]
rejoining did NOT fix it

**Comment by RobinRattus** [comment]
This might happen because i joined in survival and then did /gmc

**Comment by RobinRattus** [comment]
![grafik](https://user-images.githubusercontent.com/78902172/170371511-261bb5cd-62dd-46e3-917a-d18374b17afb.png)
It does infact work if you spawn in creative mode
![grafik](https://user-images.githubusercontent.com/78902172/170371570-6050b9d5-54af-4319-b54e-e6315099183c.png)
(1.8 server, it reset 1 enchant to prot)

**Comment by return-true-if-false** [comment]
Can you try this again and confirm this is still an issue

**Comment by return-true-if-false** [comment]
If this is still an issue please open a new issue
