### ISSUE TITLE
Lore Editor (1.16) deletes old color codes like §1Test

### ISSUE THREAD

**Issue by RobinRattus** [Ruukas97/Creative-Editor#16]

**Comment by RobinRattus** [comment]
Like if an item had color in its lore text its gone after opening the lore editor

**Comment by return-true-if-false** [comment]
So if i have color in the lore and then I open the lore editor the color disappears? (even before pressing save?)

**Comment by return-true-if-false** [comment]
Please open a new issue if this is still a problem
