### ISSUE TITLE
[1.16] Potion Amplifiers and Custom Potion Color are not working correctly

### ISSUE THREAD

**Issue by CatzRule81** [Ruukas97/Creative-Editor#18]
On the 1.16.5 version, custom potion effects that have an amplifier of 1b (level 2 effects) are not parsed correctly and get reset to their regular non-amplified versions.

Additionally, custom potion colors are being overwritten by the "Potion" NBT tag. This has so far only been proven on a server, and I have not tested it on a single player world yet to see if the issue persists there.

I am using the latest 1.16 release at the time of this post.

If further information is necessary, please let me know.

**Comment by return-true-if-false** [comment]
What do you mean overwritten? When setting a potion amplifier does it overwrite the custom colors?

**Comment by CatzRule81** [comment]
> What do you mean overwritten? When setting a potion amplifier does it overwrite the custom colors?

I'm talking about the actual "Potion" tag, not "CustomPotionEffects", this is what overrides the potion color. It could also be something with CustomPotionColor being a negative value.

**Comment by return-true-if-false** [comment]
Thanks, I'll look into it

**Comment by return-true-if-false** [comment]
I can't reproduce this in singleplayer, can you try in singleplayer and make sure it's not just a server issue?

**Comment by return-true-if-false** [comment]
Can you please try in singleplayer with the latest version from github and see if this is still an issue?

**Comment by return-true-if-false** [comment]
Reopen the issue if you manage to reproduce with latest from github
